import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'
import {Row, Col} from 'reactstrap'

export default function CarDetailing () {

    const phone = "(205)-861-3320"
    const email = "BlackWarriorCleaningPros@gmail.com"
    const interior_description = "PUT DESCRIPTION HERE BLAH BLAH BLAH BLAH OR PICTURES"

    return (
        
        <div className={styles.softwash}>
            <Head>
                <title>Black Warrior Cleaning Pros</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.softwashHeader}>
                <h1>Car Detailing</h1>
                <h3>Get A Quote</h3>
                <h5>{phone} | {email}</h5>
            </div>
            
 
            
            <div className={styles.about}>
                <h3>Car Services</h3>
                <div className={styles.divider5}/>
                <p>{interior_description}</p>
            </div>
            

            <div className={styles.softWashServices}>
                <h2>Car Services</h2>
                <div className={styles.divider3}/>
                <Row className={styles.swRow}>
                    <Col className={styles.serviceBox} xs="12" lg="5">
                        <h4>Roof</h4>
                         <p>We use a safe mixture of mild chemicals and low water pressure to remove organic buildup. This increases the condition and lifetime of your roof without damaging your shingles or metal work. </p>
                    </Col>
                    <Col className={styles.serviceBox} xs="12" lg="5">
                        <h4>Siding</h4>
                         <p>Soft wash formula specific to the type of siding that you have, whether painted wood, vinyl, masonry or anything in between. </p>
                    </Col>
                     
                    
                </Row>

                <div className={styles.softWashContact}>
                    <h2>Contact Us</h2>
                    <div className={styles.divider6}/>
                    <h2>{phone}</h2>
                    <h2>{email}</h2>
                </div>
            </div>

        </div>
        
    )
}