import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CustomCarousel from '../components/Carousel'
import { Container, 
  Row, 
  Col, 
  Card, 
  CardBody, 
  CardSubtitle, 
  CardText, 
  CardTitle, 
  Button, 
  CardImgOverlay} 
  from 'reactstrap'




export default function Home() {

  const cardList = [
    {
      cardName : "Home Soft Washing",
      img: "/assets/house_clean5.jpg",
      
    },
    {
      cardName : "Pressure Washing",
      img: ""
    },
    { 
      cardName : "Roof Washing",
      img: ""
    }
  ]

  const cardList2 = [
    {
      cardName : "Home Soft Washing",
      img: "/assets/house_clean5.jpg",
      description: "Soft washing for dirty homes is good for blah blah"
    },
    {
      cardName : "Pressure Washing",
      img: "",
      description: "Presure washing for dirty homes is good for blah blah"

    },
    { 
      cardName : "Roof Washing",
      img: "",
      description: "Roof washing for dirty homes is good for blah blah"

    }
  ]

  return (
    <div className={styles.container}>
      <Head>
        <title>Black Warrior Cleaning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <main className={styles.main}>
       
          {/* <CustomCarousel className={styles.carousel}/> */}
          <div className={styles.headerContainer}>
            <h1>BLACK WARRIOR CLEANING</h1>
            <h4>Tuscaloosa based cleaning services, for homes and businesses.</h4>
            <h3>Contact Us</h3>
            <h2>205-555-5555</h2>
            <h2>emailhere?@email.com</h2>
          </div>
          
          <div className={styles.indexContainer}>
            <Row>
              {cardList.map((card, index) => CustomCard(card, index))}
            </Row>
          </div>

          <br/><br/>

          {/* <div className={styles.indexContainer}>
            <Row>
              {cardList2.map((card, index) => CustomCard2(card, index))}
            </Row>
          </div>

          <br/><br/> */}
          
          <div className={styles.indexContainer}>
            <Row>
              {cardList2.map((card, index) => CustomCard3(card, index))}
            </Row>
          </div>
           
    
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export function CustomCard ( card ) {
  return (
    <Col className={styles.card}>
      <Card >
      <Image
        alt="Sample"
        src={card.img}
        height= "400px"
        width= "400px"
      />
      <CardBody>
        <CardTitle tag="h5">
          {card.cardName}
        </CardTitle>
        
        <CardText>
          Some quick example text to build on the card title and make up the bulk of the card‘s content.
        </CardText>
        <Button>
          Get A Quote
        </Button>
      </CardBody>
    </Card>
    </Col>
        
  )
}


export function CustomCard2 ( card ) {
  return (
    <Col className={styles.card2}>
      <h2>{card.cardName}</h2>
      <h3>{card.description}</h3>
      <Button>See More</Button>
    </Col>
        
  )
}

export function CustomCard3 ( card ) {
  return (
    <Col className={styles.card3}>
    <Card >
    <Image
      alt="Sample"
      src={card.img}
      height= "400px"
      width= "400px"
    />
     
    <CardImgOverlay>
    <div className={styles.card3test}>
      <h2>{card.cardName}</h2>
      <h3>{card.description}</h3>
      <Button>See More</Button>
    </div>
    </CardImgOverlay>
    
     
  </Card>
  
  </Col>
    
        
  )
}